
version: '3.8'

services:
  lexos-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: lexos-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
      - FRONTEND_URL=http://localhost:5173
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}
      - ENABLE_GPU_MONITORING=${ENABLE_GPU_MONITORING:-true}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
    volumes:
      - lexos-data:/app/backend/data
      - lexos-logs:/app/logs
      - lexos-backups:/app/backups
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lexos-network
    healthcheck:
      test: ["CMD", "/usr/local/bin/docker-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  lexos-nginx:
    image: nginx:alpine
    container_name: lexos-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - lexos-ssl:/etc/nginx/ssl
    networks:
      - lexos-network
    depends_on:
      - lexos-backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lexos-monitor:
    image: prom/prometheus:latest
    container_name: lexos-monitor
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - lexos-metrics:/prometheus
    networks:
      - lexos-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'

volumes:
  lexos-data:
    driver: local
  lexos-logs:
    driver: local
  lexos-backups:
    driver: local
  lexos-ssl:
    driver: local
  lexos-metrics:
    driver: local

networks:
  lexos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
