
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'lexos-backend'
    static_configs:
      - targets: ['lexos-backend:9000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'lexos-system'
    static_configs:
      - targets: ['lexos-backend:9000']
    metrics_path: '/api/v1/system/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  - job_name: 'nginx'
    static_configs:
      - targets: ['lexos-nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
